name: QA maven project
#############

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    #env:
    #  JFROG_REPO_URL: https://vicky12345.jfrog.io/artifactory/mavan-repo/dev/arvhive/
      #ARTIFACT_PATH: mavan-repo/$(cat snapshot.txt)/
    #  JFROG_REPOSITORY: mavan-repo/dev/arvhive
      
    
    strategy:
      fail-fast: false
      matrix:
        # Override automatic language detection by changing the below list
        # Supported options are ['csharp', 'cpp', 'go', 'java', 'javascript', 'python']
        language: ['java']
    
    steps:
     - name: Get latest artifact version
       run: |
        pwd
        current_version=$(curl -s -u ${{ secrets.JF_USER }}:${{ secrets.JF_PASSWORD }} "https://vicky12345.jfrog.io/artifactory/api/storage/mavan-repo/dev/archive/?lastModified" | jq '.uri' | awk -F'[/"]' '{ print $(NF-1); }')
        current_version_new=$(echo "$current_version" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
        echo "$current_version_new"
        curl -u ${{ secrets.JF_USER }}:${{ secrets.JF_PASSWORD }} -o springboot-images-new.jar -J -L https://vicky12345.jfrog.io/artifactory/mavan-repo/dev/deploy/springboot-images-new.jar
        ls -lrth
        cp -r springboot-images-new.jar springboot-images-new-$current_version_new.jar
        curl -X PUT -u ${{ secrets.JF_USER }}:${{ secrets.JF_PASSWORD }} -T springboot-images-new-$current_version_new.jar  https://vicky12345.jfrog.io/artifactory/mavan-repo/qa/archive/
        curl -X PUT -u ${{ secrets.JF_USER }}:${{ secrets.JF_PASSWORD }} -T springboot-images-new.jar  https://vicky12345.jfrog.io/artifactory/mavan-repo/qa/deploy/
