name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Run Web App
    runs-on: ubuntu-latest
    steps:
      - name: Build Web App
        run: |
          echo "Build Web App"
          sleep 10s
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: vicky0048
          repo: github-actions
          github_token: ${{ secrets.REPOSITORY_TOKEN }}
          workflow_file_name: maven.yml
          ref: master
      - name: Deploy Web App
        run: |
          echo "Deploy Web App"
          sleep 10s
